environment:
  matrix:
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
    - PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_INSTALL_LOCN: "C:\\Miniconda35-x64"
      PY_INSTALL: "lxml"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"
      PY_INSTALL: "lxml"
    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_INSTALL_LOCN: "C:\\Miniconda"
    - PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"
      CONDA_PY: "27"
      CONDA_INSTALL_LOCN: "C:\\Miniconda"
      PY_INSTALL: "lxml"
install:
    # Use the pre-installed Miniconda for the desired arch
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda update -y -q conda
    - cmd: conda config --add channels conda-forge
    - cmd: conda install -y -q numpy pandas
    - cmd: pip install --no-cache-dir -r requirements_dev.txt
    - ps: if($env:PY_INSTALL) { pip install -q --no-cache-dir $env:PY_INSTALL }

build: false

test_script:
  - pytest
